### ISSUE TITLE
CSM failing to report all allocated nodes to BDS

### ISSUE THREAD

**Issue by morrone** [IBM/CAST#502] opened 2019-01-11 00:06 UTC
It turns out that the list of allocated nodes is being significantly truncated in the CSM's csm_transaction.log.  For instance, allocation 699077 on sierra is allocated 4296 nodes, and using csm_allocation_query we can see the full list of allocated nodes.  However, csm seems to truncate the compute node list to 200 nodes in the csm_transaction.log output.

Since the compute node list is truncated, the kibana csm plugin is overly constraining the search related to allocation 699077.

This make the the plugin not terribly useful.

We need the correct list of compute nodes in the BDS.

We are using csm 1.4.0 on sierra at this time.

**Comment by mew2057** [comment] 2019-01-18 20:35
Linking to  Issue #498, both bugs have a common issue.

**Comment by mew2057** [comment] 2019-01-30 20:54
Duplicate of #498

**Closed by mew2057** 2019-01-30 20:54 UTC
Labels: Comp: CSM, Comp: CSM.bds, PhaseFound: Customer, Sev: 3, Status: Open, Type: Defect
