### ISSUE TITLE
csm_allocation_delete state change on a failure condition

### ISSUE THREAD

**Issue by fpizzano** [IBM/CAST#69] opened 2018-05-22 13:57 UTC
csm_allocation_delete is not changing the state on a faulire condition.

```
# /opt/ibm/csm/bin/csm_allocation_query_details -a 632
---
allocation_id:                  632
primary_job_id:                 1874
secondary_job_id:               0
num_nodes:                      1
compute_nodes:
  f0n17:
num_transitions:                8
state_transitions:
  - history_time:            2018-05-22 09:54:43.871944
    state:                   deleting-mcast
  - history_time:            2018-05-22 09:46:40.173818
    state:                   deleting-mcast
  - history_time:            2018-05-21 19:19:30.43866
    state:                   deleting-mcast
  - history_time:            2018-05-21 19:17:30.026285
    state:                   deleting-mcast
  - history_time:            2018-05-21 19:15:29.470352
    state:                   deleting-mcast
  - history_time:            2018-05-21 19:14:32.313438
    state:                   running
  - history_time:            2018-05-21 19:14:01.987771
    state:                   to-running
  - history_time:            2018-05-21 19:13:39.327739
    state:                   staging-in
ssd_file_system_name:
launch_node_name:               f0n16
user_flags:
system_flags:
ssd_min:                        0
ssd_max:                        0
num_processors:                 0
num_gpus:                       0
projected_memory:               0
state:                          deleting-mcast
type:                           jsm
job_type:                       batch
user_name:                      uno
user_id:                        1060
user_group_id:                  1
user_script:                    /gpfst/jake/myexec.sh
begin_time:                     2018-05-21 19:13:39.327739
account:
comment:
job_name:                       default
job_submit_time:                2018-05-21 19:13:35
queue:                          csm_bb
requeue:
time_limit:                     0
wc_key:
isolated_cores:                 0
num_steps:      3
steps:
 - step_id:         3
   num_nodes:       1
   compute_nodes:
    - f0n17
 - step_id:         2
   end_time:        2018-05-21 19:15:16.583802
   num_nodes:       1
   compute_nodes:
    - f0n17
 - step_id:         1
   end_time:        2018-05-21 19:14:32.823289
   num_nodes:       1
   compute_nodes:
    - f0n17
...
#
```

**Comment by mew2057** [comment] 2018-05-22 17:00
Removing defect tag, behavior is as intended, but improvements can be made.

**Comment by mew2057** [comment] 2018-12-05 17:58
@fpizzano is this issue still relevant?

**Comment by mew2057** [comment] 2019-02-11 21:26
Closing as this issue is no longer relevant due to the changes to this table.

**Closed by mew2057** 2019-02-11 21:26 UTC
Labels: Comp: CSM, Comp: CSM.api, Sev: 3, Status: Verify, Type: Story, Type: Test Case Request
