### ISSUE TITLE
csm_allocation_query_details cpu_usage over unity?

### ISSUE THREAD

**Issue by morrone** [IBM/CAST#534] opened 2019-01-26 00:48 UTC
The cpu_usage numbers reported by csm_allocation_query_details may be misreported.  It seems like the numbers exceed possible wall clock time.  It is also possible that I just don't really understand what the numbers mean.  So let me run through what I am seeing.

I'll use allocation id 708924 on sierra as an example.  This job was allocated 4 nodes.

If I subtract the "begin_time" from the "history: end_time", I arrive at an elapsed allocation time of 241.302722 seconds.

The reported "cpu_usage" for the first node in the allocation, sierra10, is:

```27192317892474```

I am told that the units for cpu_usage are nanoseconds.  So if we divide by 10X9, we arrive at:

```27192.317892 seconds```

So far, so good.  The number is much larger than the elapsed wall clock time, but this number is no doubt an aggregation of individual CPUs' usage.

So the next question is: how many CPUs' usage does this represent?  The answer is not totally obvious, but I got a hint from the data in the csm-allocation-cpu* indices in Elasticsearch.  In those indices, each cpu's usage is listed individually for cpu[0-43].  I even added up the usage numbers for the allocation and node in this example, and I arrived at the same aggregate number 27192317892474 that csm_allocation_query_details provided.

So lets divide the number 27192.317892 by 44 cpus to get the average:

```618.01 seconds```

How are we getting a reported 618 average cpu seconds when the entire allocation only lasted 241 seconds?

**Comment by besawn** [comment] 2019-01-28 18:08
All of the math above looks correct to me, but there is one additional factor involved: SMT mode.

All of the "cpu_usage" accounting comes from underlying linux mechanisms that use logical cpus as the basis. For the example provided above, there are 44 physical cpu cores, but depending on SMT mode, they could be represented as 44, 88, or 176 logical cores depending on whether SMT mode is 1, 2, or 4.

For the example above, I suspect SMT mode was most likely set to 4. For CSM 1.4.0, SMT mode is controlled via the administrator owned prolog and epilog. You may be able to determine the requested SMT mode for the allocation by examining the "user_flags" and "system_flags" reported by "csm_allocation_query_details".

I think there are probably cases where it is desirable to make calculations on a per physical core basis and other times it might be desirable to calculate on a per logical core basis. Just be aware that when calculating on a per physical core basis, the accumulated cpu usage can be more than the wall clock time, depending on the SMT mode.

**Comment by morrone** [comment] 2019-01-28 18:13
How would one know whether or not to apply an SMT scaling factor given the information that CSM currently supplies in the output of the csm_allocation_query_details command?

**Comment by besawn** [comment] 2019-01-30 20:00
> How would one know whether or not to apply an SMT scaling factor given the information that CSM currently supplies in the output of the csm_allocation_query_details command?

If one has a use case where one wants to calculate usage per logical core instead of per physical core, it should be possible to determine the requested SMT mode for the allocation by examining the "user_flags" and "system_flags" reported by "csm_allocation_query_details" and looking for the smt/SMT flag requested.

OR

Don't worry about applying an SMT scaling factor, instead accept that total CPU usage per physical core can be greater than wall clock time because each physical core can do more than 1x work per second.

**Comment by besawn** [comment] 2019-02-05 18:38
Closing as working as designed, given the impact of SMT mode on the CPU usage metric behavior.

**Closed by besawn** 2019-02-05 18:38 UTC
Labels: Comp: CSM, PhaseFound: Customer

**Comment by peterwywong** [comment] 2019-02-06 17:00
Thanh and I ran CPU DGEMM on one node using the SMT1 (ST), SMT2 and SMT4 modes.
The wall clock time was about 62 seconds in all cases.
With the SMT1 mode, all cores took around the same time, the cpu usage per core reported by CSM was 62 seconds.
With the SMT2 mode, all cores also took around the same time, the cpu usage per core reported by CSM was 125 (~= 2 *62) seconds.
With the SMT4 mode, all cores also took around the same time, the cpu usage per core reported by CSM was 232 (~= 4*62) seconds.
Based on the number of active HW threads, the amount of cpu usage is adjusted accordingly.

**Comment by besawn** [comment] 2019-02-06 18:48
@peterwywong Thanks for the confirmation and test data.
